# Puerto dinámico para Railway (y 8080 para tu PC local)
server.port=${PORT:8080}

# Nombre de la app
spring.application.name=coleccion

# Conexión a la Base de Datos (lee la variable de Railway, o usa localhost en tu PC)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/coleccion_videojuegos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect